# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prototype_watchman/prototype_watchman.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman || ORIG_REF_NAME==prototype_watchman} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_processing_system7_0_0/prototype_watchman_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_processing_system7_0_0 || ORIG_REF_NAME==prototype_watchman_processing_system7_0_0} -quiet] -quiet

# XDC: bd/prototype_watchman/prototype_watchman_ooc.xdc
